spring.application.name=agence
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/agence
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
server.adress=0.0.0.0
server.port=8080
#server.port=6060
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security=ERROR
spring.session.timeout=10

